name: feathers_auth_flutter
description: A new Flutter plugin.
version: 0.0.1
homepage: https://github.com/SmarttersStudio/feathers_auth_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  socket_io_client: ^3.1.2

