name: feathers_auth_flutter
description: A new Flutter plugin.
version: 0.0.1
homepage: https://github.com/SmarttersStudio/feathers_auth_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
#  flutter: ">=1.20.0 <2.0.0"

dependencies:
  dio: ^4.0.0
  shared_preferences: ^2.0.8
